### ISSUE TITLE
loss is nan! please help me!

### ISSUE THREAD

**Issue by zzzz737** [CoinCheung/BiSeNet#96]
hello! I trained my own dataset with one classes "tunnel"! I changed the labels_info and classes in cityscapes_cv2.py! And i changed the train.py! But when i trained ,i get the loss is nan ! I don't konw why, can you solve it?
![classes](https://user-images.githubusercontent.com/69610913/99615951-50242700-2a57-11eb-9641-ce65e7bcbe15.png)
![train](https://user-images.githubusercontent.com/69610913/99615966-5914f880-2a57-11eb-9fac-40234653bb51.png)
![loss](https://user-images.githubusercontent.com/69610913/99615977-5c0fe900-2a57-11eb-9fa5-baaa20b73542.png)

**Comment by CoinCheung** [comment]
Try this: `n_cats = 2`, `lb_ignore=255`.

**Comment by zzzz737** [comment]
> Try this: `n_cats = 2`, `lb_ignore=255`.

Thanks for answer! I tried it ,it's ok!
But I don't understand! I read the code, I think your code self.n_cats=19 is not include the background, in your code you set the 255 are backgrounds! but in my dataset, i set the background is 0, why i need to set the n_cats=2, and lb_ignore=255? I am so confused!

**Comment by CoinCheung** [comment]
lb_ignore means you do not consider it during training, while background means negative samples, which will be used during training to distinguish from positive(or foreground samples).

**Comment by zzzz737** [comment]
> lb_ignore means you do not consider it during training, while background means negative samples, which will be used during training to distinguish from positive(or foreground samples).

yeah, i understand what you said, but your code what's the id of the background? the id 0-19 are the foreground, so the n_cats=19 , it doesn't include the background, right?

**Comment by CoinCheung** [comment]
Just follow the label map strategy of cityscapes at their requirement.

**Comment by zzzz737** [comment]
> Just follow the label map strategy of cityscapes at their requirement.

OK, thanks!

**Comment by CoinCheung** [comment]
I am closing this because the problem is solved.

**Comment by curryJ** [comment]
> hello! I trained my own dataset with one classes "tunnel"! I changed the labels_info and classes in cityscapes_cv2.py! And i changed the train.py! But when i trained ,i get the loss is nan ! I don't konw why, can you solve it?
> ![classes](https://user-images.githubusercontent.com/69610913/99615951-50242700-2a57-11eb-9641-ce65e7bcbe15.png)
> ![train](https://user-images.githubusercontent.com/69610913/99615966-5914f880-2a57-11eb-9fac-40234653bb51.png)
> ![loss](https://user-images.githubusercontent.com/69610913/99615977-5c0fe900-2a57-11eb-9fa5-baaa20b73542.png)

Hello! I have the same issue too! And I follow the solution of this issue,the loss is not nan and the code can run correctly.
Could you tell me your result?Is it good? My dataset is like yours,which just includes one class and this background is 0.

**Comment by zzzz737** [comment]
> @zzzz737 could you tell me how exactly you solved it?
> 
> 1. What is the loss function that you used?
> 2. What is your cityscapes_cv2.py look like?
> 3. How many classes did you create your network with?
> 
> It would be really nice if you could share me these 3 details. I also have a 2 class problem very similar to yours. I used the following:
> 
> 1. OHEM CE loss
> 2. `train-id "1" for background` and `traind-id "2" for monorail`, and `lb_ignore=255`. Monorail refers to the object that I am interested in.
> 
> > code snippets from cityscapes_cv2.py
> 
> ```
> labels_info = [
>     {"hasInstances": False, "category": "void", "catid": 0, "name": "background", "ignoreInEval": False, "id": 0, "color": [0, 0, 0], "trainId": 1},
>     {"hasInstances": True, "category": "void", "catid": 1, "name": "monorail", "ignoreInEval": False, "id": 1, "color": [128, 64,128], "trainId": 2},
> ]
> ```
> 
> ```
> self.n_cats = 2
> self.lb_ignore = 255
> ```
> 
> 1. I created network with 2 classes in my train_amp.py
> 
> code snippets from train_amp.py
> 
> ```
> def set_model():
>     net = model_factory[cfg.model_type](2)
> ```
> 
> I also verified my labeling and I think there is no mistake regarding the same as well. I still get Nan for all my losses
> `INFO logger.py(42): iter: 100/80000, lr: 0.006908, eta: 23:18:14, time: 106.05, loss: nan, loss_pre: nan, loss_aux0: nan, loss_aux1: nan`

you can try to set your labels_info, the background "trainId":0, and monorail "trainId":1.

**Comment by Eashwar93** [comment]
@zzzz737 Thanks. I trained it that way and it still doesn't work with AMP using the file train_amp.py while the normal training works with train.py
